apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-recommender
  namespace: "2401007"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-recommender
  template:
    metadata:
      labels:
        app: course-recommender
    spec:
      imagePullSecrets:
        - name: nexus-secret

      containers:
        - name: course-recommender
          image: 127.0.0.1:30085/2401007/course-recommender:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
