apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-recommender
  template:
    metadata:
      labels:
        app: course-recommender
    spec:
      containers:
      - name: course-recommender
        image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401007/course-recommender:latest
        ports:
        - containerPort: 8501
