apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-recommender
  namespace: 2401007
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-recommender
  template:
    metadata:
      labels:
        app: course-recommender
    spec:
      containers:
        - name: course-recommender
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/2401007/course-recommender:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          command: ["streamlit"]
          args:
            ["run", "frontend_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]

          readinessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8501
            initialDelaySeconds: 40
            periodSeconds: 20

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
