apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: course-recommender-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: course-recommender.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: course-recommender-service
                port:
                  number: 80
