apiVersion: v1
kind: Service
metadata:
  name: course-recommender-service
  namespace: "2401007"
spec:
  type: NodePort
  selector:
    app: course-recommender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30007
