apiVersion: v1
kind: Service
metadata:
  name: course-recommender-service
spec:
  type: NodePort
  selector:
    app: course-recommender
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30007
